### ISSUE TITLE
last minute submission for SciPy 2016

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy-2016#1]
Dear @MDAnalysis/scipy2016 ,

I submitted a proposal for a talk at [SciPy 2016](http://scipy2016.scipy.org) literally at the last minute (the deadline is today 5pm PDT...). I apologize for adding you as authors and submitting without feedback; I hope you're ok with what I submitted and with appearing on the proposal. If not, please email me and I try to fix-up things by emailing them directly. 

The submission is for the domain specific Mini Symposium on _Biology and Medicine_ --- the closest to what the majority of use cases for MDAnalysis seem to be. If the proposal is accepted, we will also have the opportunity to submit a short conference proceedings paper but we can discuss this when we know more.

Oliver

**Comment by tylerjereddy** [comment]
Sounds good. I'll be giving a 3 hour tutorial on computational geometry at [PyCon 2016](https://us.pycon.org/2016/).

**Comment by orbeckst** [comment]
The abstract got accepted

> Your abstract  was reviewed by the Program Committee and we are happy to inform you that it has been accepted as a talk for SciPy 2016. Congratulations!

There will also be a short proceedings paper – see issue #2.
